org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=false


android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=37.0
android.overridePathCheck=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
kotlin.code.style=official
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.native.binary.smallBinary=true
kotlin.native.ignoreDisabledTargets=true
kotlin.incremental=true
kotlin.incremental.multiplatform=true
kotlin.incremental.jvm.fir=true
kotlin.incremental.js=true
kotlin.incremental.js.klib=true
kotlin.incremental.native=true
kotlin.incremental.wasm=true
org.jetbrains.compose.experimental.macos.enabled=true
kotlin.apple.xcodeCompatibility.nowarn=true
